"""Shared protocol package for remote-mcp-linkedin."""

from .schemas import (
    ALL_PROFILE_SECTIONS,
    DEFAULT_NETWORK_DEGREES,
    DEFAULT_PROFILE_SECTIONS,
    PROTOCOL_VERSION,
    BridgeAck,
    BridgeCommand,
    BridgeError,
    BridgeHello,
    BridgeResultMessage,
    ErrorCode,
    NetworkDegree,
    NetworkSearchRequest,
    ProfileGetRequest,
    ProfileSection,
    RawNetworkResult,
    RawProfileResult,
    SectionExtractionError,
)

__all__ = [
    "ALL_PROFILE_SECTIONS",
    "DEFAULT_NETWORK_DEGREES",
    "DEFAULT_PROFILE_SECTIONS",
    "PROTOCOL_VERSION",
    "BridgeAck",
    "BridgeCommand",
    "BridgeError",
    "BridgeHello",
    "BridgeResultMessage",
    "ErrorCode",
    "NetworkDegree",
    "NetworkSearchRequest",
    "ProfileGetRequest",
    "ProfileSection",
    "RawNetworkResult",
    "RawProfileResult",
    "SectionExtractionError",
]
